# Generated by Django 4.1.5 on 2023-01-24 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'List of Airports',
            },
        ),
        migrations.CreateModel(
            name='Beverages',
            fields=[
                ('beverages_id', models.IntegerField(primary_key=1, serialize=False)),
                ('beverages_name', models.CharField(max_length=50)),
                ('beverages_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'List of Flights',
            },
        ),
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('flight_code', models.CharField(max_length=50)),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('no_of_stops', models.IntegerField(default=0)),
                ('economy_seats', models.IntegerField(default=0)),
                ('business_seats', models.IntegerField(default=0)),
                ('firstclass_seats', models.IntegerField(default=0)),
                ('economy_price', models.FloatField(default=0)),
                ('business_price', models.FloatField(default=0)),
                ('firstclass_price', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('flight_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.flight')),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From_Airport', to='adminapp.airport')),
                ('stops', models.ManyToManyField(blank=True, null=True, to='adminapp.airport')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To_Airport', to='adminapp.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.IntegerField(primary_key=1, serialize=False)),
                ('food_name', models.CharField(max_length=50)),
                ('food_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'First Class'), ('2', 'Business Class'), ('3', 'Economy Class')], default=3, max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('adults', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('infants', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('1', 'Successful'), ('2', 'Cancelled')], default=2, max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
                ('beverages', models.ManyToManyField(blank=True, null=True, to='adminapp.beverages')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.flightdetails')),
                ('food', models.ManyToManyField(blank=True, null=True, to='adminapp.food')),
            ],
            options={
                'verbose_name_plural': 'List of Reservations',
            },
        ),
    ]
