# Generated by Django 4.1.3 on 2022-12-14 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetails',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='adminapp.flight'),
        ),
        migrations.AlterField(
            model_name='ticketinfo',
            name='no_seats',
            field=models.IntegerField(default=1),
        ),
    ]
